### ISSUE TITLE
Fix Firebase Authentication Failure

### ISSUE THREAD

**Issue by SwayamDhanawade** [Anikesh02/AL-frontend#4]
The Firebase authentication system is not functioning as expected. Users are unable to sign in or sign up, and the authentication process fails without returning appropriate error messages. This issue impacts both new and returning users, preventing them from accessing the application features.

**Comment by Anikesh02** [comment]
> The Firebase authentication system is not functioning as expected. Users are unable to sign in or sign up, and the authentication process fails without returning appropriate error messages. This issue impacts both new and returning users, preventing them from accessing the application features.

Would you like to work on this issue?

**Comment by SwayamDhanawade** [comment]
> > The Firebase authentication system is not functioning as expected. Users are unable to sign in or sign up, and the authentication process fails without returning appropriate error messages. This issue impacts both new and returning users, preventing them from accessing the application features.
> 
> Would you like to work on this issue?

Yes, I would like to try

**Comment by Anikesh02** [comment]
@SwayamDhanawade Assigned
